version: "3"
services:
  homeru_bot:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /homeru_bot
    volumes:
      - .:/homeru_bot
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    image: homeru_bot-image
    container_name: homeru_bot-container
    env_file: .env
    tty: true
