version: "3"
services:
  homeru_bot:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /homeru_bot
    volumes:
      - .:/homeru_bot
    image: homeru_bot-image
    container_name: homeru_bot-container
    tty: true
    env_file: .env
