[tool.black]
target-version = ["py310"]
line-length = 100
skip-string-normalization = true
include = '¥.pyi?$'

[tool.isort]
line_length = 100
force_grid_wrap = 0
include_trailing_comma = true
multi_line_output = 3
use_parentheses = true
